docs/getting_started/fhevm/coprocessor/contracts.md
fhevm-engine/Cargo.lock
fhevm-engine/coprocessor/Cargo.toml
fhevm-engine/coprocessor/README.md
fhevm-engine/coprocessor/src/daemon_cli.rs
fhevm-engine/coprocessor/src/tfhe_worker.rs
fhevm-engine/fhevm-engine-common/Cargo.toml
fhevm-engine/fhevm-go-coproc/fhevm/api.go

- **feat: make coprocessor sync interval configurable**
- Currently, this value is hardcoded to 10s. This could be too long,
leading to artificial delay in the ciphertext being available in the
coprocessor db.
- Now, make it configurable via environment variable.
- **feat: make worker job polling interval config**
- Previously, the value was hardcoded to 5000ms. This could lead to long
wait between processing jobs and hence a delay in result being
available in the coprocessor db.
- Now, make this interval configurable via command line argument. Can be
fine tuned as per needed performance.
- **chore: bump version to v0.1.2**
Closes #169

Make the polling interval configurable.

---

fhevm-engine/scheduler/src/dfg/scheduler.rs

fixes #168 
- We must ensure that set_server_key is always configured for every computation thread.
It was observed that when the number of computations is only one, the `comps.par_iter` executes this computation in the current thread. However, since broadcast invokes are triggered only for Rayon threads, the local_storage of the current thread is not initialized with the server key.
- Additionally, to prevent blocking the Tokio executor, the Rayon execution is wrapped in spawn_blocking so .`await` allows us to yield.

fix(schedule): prevent panicking in loop_schedule routine

---

contracts/gateway/GatewayContract.sol
contracts/gatewayLib/lib/Gateway.sol
contracts/package-lock.json
contracts/package.json
contracts/test/asyncDecrypt.ts
contracts/test/upgrades/upgrades.ts
fhevm-engine/Cargo.lock
fhevm-engine/coprocessor/Cargo.toml
fhevm-engine/executor/Cargo.toml
fhevm-engine/fhevm-engine-common/Cargo.toml
fhevm-engine/scheduler/Cargo.toml

This PR makes the code of GatewayContract and Gateway library a lot more complex than previously, but this was needed since KMS did not implement the specific data handling in the trustless decryption case, and we decided not to change anything from KMS side. Since the trustless case became more complex, it consumes more gas, but we had no other option since we want the KMS to be agnostic to wether decryption was requested in trustless or trusted mode.
To mitigate the increase in gas cost, I implementend one of the optimizations we talked about : I am no longer doing a KMSVerifier call inside the GatewayContract in the trustless case (since in this case we assume that the dapp will do the verification itself).
Some other more minor improvements include : switching the `external` modifier …

fix: make GatewayContract compatible with current KMS in trustless case

---

docs/getting_started/fhevm/coprocessor/configuration.md
fhevm-engine/Cargo.lock
fhevm-engine/coprocessor/Cargo.toml
fhevm-engine/coprocessor/src/daemon_cli.rs
fhevm-engine/coprocessor/src/lib.rs
fhevm-engine/coprocessor/src/tests/utils.rs
fhevm-engine/coprocessor/src/tracing.rs

fixes #130 
- Add new CLI option `--service-name`
- Set the service name in setting OTLP traces service name

feat: Use config.service-name in coprocessor OTLP traces

---

fhevm-engine/fhevm-go-native/fhevm/api.go

fixes #201 
- Previously, the variables declared by a “for” loop were created once and updated by each iteration. In Go 1.22, each iteration of the loop creates new variables, to avoid accidental sharing bugs. The [transition support tooling](https://tip.golang.org/wiki/LoopvarExperiment#my-test-fails-with-the-change-how-can-i-debug-it) described in the proposal continues to work in the same way it did in Go 1.2
- src: https://tip.golang.org/doc/go1.22
- Although, it's fixed in latest golang version, it's cheaper to avoid the bug.  
Result:
```
DEBUG[12-19|10:13:58.842] Add operation                            module="fhevm:sync compute" op=FHE_TRIVIAL_ENCRYPT handle=29c43b..f40300
DEBUG[12-19|10:13:58.842] Add operation                            module="fhevm:sync compute" …
```

fix(native): ensure buckets use valid references

---

fhevm-engine/fhevm-go-native/fhevm/api.go
fhevm-engine/fhevm-go-native/fhevm/fhelib.go
fhevm-engine/fhevm-go-native/fhevm/logger.go

Simplifies debugging by adding trace logs for key actions such as `execute`, `commit`, `queue`, `flush`, and `compute`.
- Most traces are now logged at the `log.debug` level with a few in `log.info`.
- In Geth, enable debug-level logging using the `--verbosity 4` CLI parameter.
- `grep fhevm`: Display all FHEVM-related logs.
- `grep handle=59b4f9`: Filter logs by specific handle.
- `grep 'sync compute'`: Display input and output of `grpc.SyncCompute`.
```
DEBUG[12-18|12:21:25.859] Add operation                            module="fhevm:sync compute" op=FHE_TRIVIAL_ENCRYPT handle=59b4f9..500300
INFO [12-18|12:21:25.859] Sending grpc request                     module="fhevm:sync compute" computations=1 "compressed ciphertexts"=0
INFO [12-18|12:21:25.864] Response …
```

feat(native): enhance traceability with additional logs for better debugging

---

contracts/contracts/ACL.sol
contracts/test/acl/acl.t.sol

This PR adds  the possibility to delegate and revoke ACL authorization, as per issue #265 we can add delegation for a list of contract addresses of length of up to 10.
Note: this PR also now forbids the possibility to call `allowForDecryption` with an empty list.

feat: delegation and revoke functions and events

---

fhevm-engine/listener/Cargo.toml
fhevm-engine/listener/src/bin/main.rs

Resolve error:
```
fhevm-engine$ cargo build --release
Compiling alloy-json-rpc v0.3.6
Compiling alloy-rpc-types-eth v0.3.6
error[E0277]: the trait bound `winnow::stream::stateful::Stateful<&'i str, RecursionCheck>: StreamIsPartial` is not satisfied because the trait comes from a different crate version
--> /home/tech/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-dyn-abi-0.8.19/src/coerce.rs:169:17
|
169  |                 take_while(min.., move |c: char| !unsafe { chs.get_unchecked(..l) }.contains(&c))
```

chore: bump alloy version

---

fhevm-engine/coprocessor/src/db_queries.rs
fhevm-engine/coprocessor/src/server.rs
fhevm-engine/coprocessor/src/tests/errors.rs
fhevm-engine/fhevm-db/migrations/20250205000000_drop_output_type_in_computations.sql
fhevm-engine/fhevm-engine-common/src/tfhe_ops.rs

it was only written to table but never used by tfhe_workers

chore: remove computations.output_type

---

fhevm-engine/Cargo.lock
fhevm-engine/fhevm-db/migrations/20250221112128_gw_listener_last_block.sql
fhevm-engine/gw-listener/.sqlx/query-4348b12a11ea6fcb102d97b1979b63ac167f55188496f006abce0ee1159b6663.json
fhevm-engine/gw-listener/.sqlx/query-5d0594aefc96b09bbfc06cc5bfee7a066b01630afec98b2a8407e05fb79466b6.json
fhevm-engine/gw-listener/.sqlx/query-74b048fe6f93de73a64257cd1f4804e7f83041922df6494ebaaa754630bd8d2d.json
fhevm-engine/gw-listener/Cargo.toml
fhevm-engine/gw-listener/src/bin/gw_listener.rs
fhevm-engine/gw-listener/src/gw_listener.rs
fhevm-engine/gw-listener/src/lib.rs
fhevm-engine/gw-listener/tests/gw_listener_tests.rs
fhevm-engine/transaction-sender/src/bin/transaction_sender.rs
fhevm-engine/transaction-sender/src/lib.rs
fhevm-engine/transaction-sender/src/ops/add_ciphertext.rs
fhevm-engine/transaction-sender/src/ops/verify_proof.rs
fhevm-engine/transaction-sender/src/transaction_sender.rs
fhevm-engine/transaction-sender/tests/common.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

This commit adds input poofs handling in the gw-listener. It supports restarting from the last seen block in case of a crash or stop of the service.
We assume that the ZKPoKManager can handle proof requests that were already completed, meaning that redoing some requests won't have negative effects. That allows us to only remember the last **seen** block number. For more information on the ZKPoKManager, see:
```@dev This means a "late" response will not be reverted, just ignored```
https://github.com/zama-ai/gateway-l2/blob/main/contracts/ZKPoKManager.sol#L125
Error handling will be improved in future commits. More tests will be
added too.
Reorg handling is also a topic for a future commit.

feat: first version of input proofs in gw-listener

---

fhevm-engine/Cargo.lock
fhevm-engine/transaction-sender/src/bin/transaction_sender.rs
fhevm-engine/transaction-sender/src/ops/add_ciphertext.rs
fhevm-engine/transaction-sender/src/ops/verify_proof.rs
fhevm-engine/transaction-sender/src/transaction_sender.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

* data structure name of `EIP712ZKPoK`
* `contractChainId` instead of `chainId` in EIP712ZKPoK
* use the GW chain ID in the EIP712 domain
Honour the `verify_proof_resp_database_channel` and the `add_ciphertexts_database_channel` config options.

fix: EIP712 verify proof signature

---

fhevm-engine/coprocessor/src/tests/random.rs
fhevm-engine/fhevm-engine-common/src/tfhe_ops.rs

Previous uses 2-bit generator bounded to single bit then compares to 0 to get random boolean which is very likely less efficient. FheBool generator is now available instead.

Use the TFHE boolean random generator instead of workaround

---

fhevm-engine/gw-listener/src/gw_listener.rs
fhevm-engine/transaction-sender/src/transaction_sender.rs

If the event stream returns None, consider the stream closed and resubscribe to the event stream.

fix(gw-listener): reconnect on event stream close

---

fhevm-engine/fhevm-keys/sns_pk
fhevm-engine/fhevm-keys/sns_sk
fhevm-engine/sns-executor/README.md
fhevm-engine/sns-executor/src/bin/sns_worker.rs
fhevm-engine/sns-executor/src/bin/utils/daemon_cli.rs
fhevm-engine/sns-executor/src/executor.rs
fhevm-engine/sns-executor/src/keyset.rs
fhevm-engine/sns-executor/src/lib.rs
fhevm-engine/sns-executor/src/tests/mod.rs

- fixes #328 
- Update example sns keys in fhevm-keys with `tfhe 1.0.0`
An example run:
```
/target/release/sns_worker --tenant-api-key a1503fb6-d79b-4e9e-826d-44cf262f3e05 --pg-listen-channel notify_sns_worker --pg-notify-channel notify_computed
```

 Use tenant-api-key in SnS worker

---

fhevm-engine/Cargo.lock
fhevm-engine/coprocessor/Dockerfile
fhevm-engine/fhevm-db/Dockerfile
fhevm-engine/fhevm-engine-common/src/tfhe_ops.rs
fhevm-engine/gw-listener/Cargo.toml
fhevm-engine/gw-listener/build.rs
fhevm-engine/transaction-sender/Cargo.toml
fhevm-engine/transaction-sender/build.rs
fhevm-engine/zkproof-worker/src/verifier.rs

In order to do so:
* Update to rust:1.85.0-bookworm and debian:bookworm-slim.
* Specify a solc version of 0.8.28 due to libc and libstdc++ issues
with the rust Docker image.
The idea of updating to bookworm is that the bullseye version is now old.

chore: commit missing Cargo.lock updates

---

fhevm-engine/transaction-sender/.sqlx/query-472ce6f9493ad23d87b20cd214ba2c9d511d5f39a248f94f7112fb40668f73b7.json
fhevm-engine/transaction-sender/contracts/CiphertextManager.sol
fhevm-engine/transaction-sender/contracts/ZKPoKManager.sol
fhevm-engine/transaction-sender/src/ops/verify_proof.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

Resolves: https://github.com/zama-ai/httpz-backend/issues/406
Also, use the `CoprocessorSignerAlreadyResponded` event instead of `CoprocessorHasAlreadySigned` to match the ZKPoKManager contract.

feat: call rejectProofResponse() if ZKPoK fails

---

fhevm-engine/Cargo.lock
fhevm-engine/transaction-sender/src/bin/transaction_sender.rs
fhevm-engine/transaction-sender/src/lib.rs
fhevm-engine/transaction-sender/src/ops/add_ciphertext.rs
fhevm-engine/transaction-sender/src/ops/allow_handle.rs
fhevm-engine/transaction-sender/src/ops/verify_proof.rs
fhevm-engine/transaction-sender/tests/add_ciphertext_tests.rs
fhevm-engine/transaction-sender/tests/allow_handle.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

Use a `CachedNonceManager` instead of the simple one. That allows for concurrent transactions to be sent from the same account.
Add the `txn_receipt_timeout_secs` configuration option to make sure we don't wait for receipts for too long and timeout is configurable.
Note that above solution might not be enough as if some txns fail, say due to not being able to send them to the mempool and the nonce being already incremented, the nonce will be out of sync. One solution is to re-create the provider every time an error occurs. More investigation is needed to see if this is the right approach.

fix(txn-sender): concurrent txns 1st step

---

fhevm-engine/Cargo.lock
fhevm-engine/fhevm-listener/.gitignore
fhevm-engine/fhevm-listener/Cargo.toml
fhevm-engine/fhevm-listener/build.rs
fhevm-engine/gw-listener/src/bin/gw_listener.rs
fhevm-engine/transaction-sender/src/bin/transaction_sender.rs
fhevm-engine/transaction-sender/tests/add_ciphertext_tests.rs
fhevm-engine/transaction-sender/tests/allow_handle.rs
fhevm-engine/transaction-sender/tests/common.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

Since txn-sender waits for txn receipts, it is better to use WS instead of HTTP and polling. This also makes it faster to get the receipts.
Resolves https://github.com/zama-ai/httpz-backend/issues/443

fix(txn-sender): use a WS provider instead of HTTP

---

fhevm-engine/transaction-sender/src/bin/transaction_sender.rs
fhevm-engine/transaction-sender/src/lib.rs
fhevm-engine/transaction-sender/src/nonce_managed_provider.rs
fhevm-engine/transaction-sender/src/ops/add_ciphertext.rs
fhevm-engine/transaction-sender/src/ops/allow_handle.rs
fhevm-engine/transaction-sender/src/ops/mod.rs
fhevm-engine/transaction-sender/src/ops/verify_proof.rs
fhevm-engine/transaction-sender/src/transaction_sender.rs
fhevm-engine/transaction-sender/tests/add_ciphertext_tests.rs
fhevm-engine/transaction-sender/tests/allow_handle.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

Since a nonce could be incremented in the `CachedNonceManager` when
transaction sending fails (say due to the GW being down or the
connection to it being lost), in this commit we introduce the
`NonceManagedProvider`. It contains a `CachedNonceManager` inside of it.
In case of any error, we re-create the `CachedNonceManager`, forcing it
to fetch the latest nonce from the GW and start from there. That allows
us to send txns concurrently in a safe way.
Add a configuration option for the required confirmations with a default
value of 0. Reasoning is that we assume the GW to be a rollup and we are
not waiting for hard finality on it.
We also simplify code by putting the DB pool and provider inside of the
the operations data structures.

feat(txn-sender): nonce management on errors

---

fhevm-engine/zkproof-worker/src/verifier.rs

Add a 64 bit chain ID unsigned value (in big endian) to the handle, making the handle format the following, in order from first to last byte:
* 21 bytes from hashing the ciphertext
* 1 byte index
* 8 bytes of chain ID
* 1 byte of ciphertext type
* 1 byte of version
Resolves: https://github.com/zama-ai/httpz-backend/issues/436
Implementation taken from the following PR from @goshawk-3: https://github.com/zama-ai/httpz-backend/pull/458/files#
Changing the chain ID type from i32 to u64 throughout the codebase will be done in a separate commit.

feat: add chain ID to handles

---

fhevm-engine/coprocessor/Cargo.toml
fhevm-engine/coprocessor/Dockerfile
fhevm-engine/coprocessor/src/bin/utils.rs
fhevm-engine/fhevm-db/Dockerfile
fhevm-engine/fhevm-db/initialize_db.sh

- Add a binary (utils) that extracts ServerKey without noise squashing keys.
- Update db-migration docker image to build and use `utils` executable to do conversion on deployment

chore: add binary for helper tasks like ServerKey conversion

---

contracts/hardhat.config.ts

This is required for smart contract verification on our Internal dev blockscout.

feat: add etherscan URLs for zwsDev

---

fhevm-engine/transaction-sender/contracts/InputVerification.sol
fhevm-engine/transaction-sender/src/ops/verify_proof.rs
fhevm-engine/transaction-sender/src/transaction_sender.rs
fhevm-engine/transaction-sender/tests/verify_proof_tests.rs

Use the `CoprocessorSignerAlreadyVerified` and
`CoprocessorSignerAlreadyRejected` errors s.t. we are in sync with the
Gateway contracts.

fix: use CoprocessorSignerAlreadyVerified/Rejected

---

fhevm-engine/fhevm-engine-common/src/telemetry.rs
fhevm-engine/sns-executor/src/aws_upload.rs
fhevm-engine/sns-executor/src/bin/sns_worker.rs
fhevm-engine/sns-executor/src/bin/utils/daemon_cli.rs
fhevm-engine/sns-executor/src/executor.rs
fhevm-engine/sns-executor/src/lib.rs

Add a max_concurrent_uploads conf parameter to control the concurrency limit. Emit a warning when the maximum limit is reached to prompt manual intervention.
The uploading task is triggered as soon as the ct128 is computed.
fixes #568

feat(sns-worker): enable parallel uploads of ciphertexts to S3 buckets

---

fhevm-engine/Cargo.lock
fhevm-engine/Cargo.toml
fhevm-engine/coprocessor/Cargo.toml
fhevm-engine/fhevm-engine-common/Cargo.toml
fhevm-engine/fhevm-engine-common/src/telemetry.rs
fhevm-engine/fhevm-listener/Cargo.toml
fhevm-engine/gw-listener/Cargo.toml
fhevm-engine/gw-listener/src/gw_listener.rs
fhevm-engine/sns-executor/Cargo.toml
fhevm-engine/test-harness/Cargo.toml
fhevm-engine/transaction-sender/Cargo.toml
fhevm-engine/zkproof-worker/Cargo.toml

Instead, rely on Cargo.lock for pinning versions.
Also, update otel to 0.29 and redo the code as it no longer compiles.
Specify more common dependencies in the workspace Cargo.toml file.

chore(deps): do not pin deps in Cargo.toml
